DISTNAME=	jakllsch-meta-meta-0.0.0.2012.10.20.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - metapackage
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	jakllsch-meta-misc-[0-9]*:../../jakllsch/jakllsch-meta-misc
DEPENDS+=	jakllsch-meta-gui-base-[0-9]*:../../jakllsch/jakllsch-meta-gui-base
DEPENDS+=	jakllsch-meta-fonts-[0-9]*:../../jakllsch/jakllsch-meta-fonts
DEPENDS+=	jakllsch-meta-gui-[0-9]*:../../jakllsch/jakllsch-meta-gui
DEPENDS+=	jakllsch-meta-netbsd-developer-[0-9]*:../../jakllsch/jakllsch-meta-netbsd-developer
DEPENDS+=	jakllsch-meta-pkgsrc-developer-[0-9]*:../../jakllsch/jakllsch-meta-pkgsrc-developer

.include "../../mk/bsd.pkg.mk"
