DISTNAME=	jakllsch-meta-gui-0.0.0.2014.02.18.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - GUI
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	transset-[0-9]*:../../x11/transset
DEPENDS+=	xbomb-[0-9]*:../../games/xbomb
DEPENDS+=	xtris-[0-9]*:../../games/xtris
DEPENDS+=	xdaliclock-[0-9]*:../../time/xdaliclock
DEPENDS+=	sunclock-[0-9]*:../../time/sunclock
DEPENDS+=	glclock-[0-9]*:../../time/glclock

DEPENDS+=	pavucontrol-[0-9]*:../../audio/pavucontrol
DEPENDS+=	firefox24-[0-9]*:../../www/firefox24
DEPENDS+=	mplayer-[0-9]*:../../multimedia/mplayer
DEPENDS+=	geeqie-[0-9]*:../../graphics/geeqie

DEPENDS+=	gliv-[0-9]*:../../graphics/gliv

DEPENDS+=	thunderbird-[0-9]*:../../mail/thunderbird

DEPENDS+=	evince-[0-9]*:../../print/evince
DEPENDS+=	epdfview-[0-9]*:../../print/epdfview
DEPENDS+=	xpdf-[0-9]*:../../print/xpdf
DEPENDS+=	djview4-[0-9]*:../../graphics/djview4
DEPENDS+=	calibre-[0-9]*:../../misc/calibre

#DEPENDS+=	gpsdrive-[0-9]*:../../geography/gpsdrive

DEPENDS+=	xephem-[0-9]*:../../x11/xephem
DEPENDS+=	celestia-[0-9]*:../../misc/celestia
DEPENDS+=	stellarium-[0-9]*:../../misc/stellarium
DEPENDS+=	gpredict-[0-9]*:../../ham/gpredict

DEPENDS+=	gnome-platform-[0-9]*:../../meta-pkgs/gnome-platform
DEPENDS+=	gstreamer0.10-plugins-[0-9]*:../../meta-pkgs/gstreamer0.10-plugins
DEPENDS+=	gimp-[0-9]*:../../graphics/gimp
DEPENDS+=	cheese-[0-9]*:../../graphics/cheese
DEPENDS+=	gucharmap-[0-9]*:../../fonts/gucharmap
DEPENDS+=	nautilus-[0-9]*:../../sysutils/nautilus
DEPENDS+=	ekiga-[0-9]*:../../net/ekiga
DEPENDS+=	evolution-[0-9]*:../../mail/evolution
DEPENDS+=	povray-[0-9]*:../../graphics/povray

DEPENDS+=	darktable-[0-9]*:../../graphics/darktable
DEPENDS+=	gtk2-engines-[0-9]*:../../x11/gtk2-engines
DEPENDS+=	openoffice3-[0-9]*:../../misc/openoffice3
DEPENDS+=	rdesktop-[0-9]*:../../net/rdesktop
DEPENDS+=	tightvncviewer-[0-9]*:../../net/tightvncviewer
DEPENDS+=	qemu-[0-9]*:../../emulators/qemu

.include "../../mk/bsd.pkg.mk"
