DISTNAME=	jakllsch-meta-gui-0.0.0.2012.02.02.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - GUI
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	transset:../../x11/transset
DEPENDS+=	xbomb:../../games/xbomb
DEPENDS+=	xtris:../../games/xtris
DEPENDS+=	xdaliclock:../../time/xdaliclock
DEPENDS+=	sunclock:../../time/sunclock
DEPENDS+=	glclock:../../time/glclock

DEPENDS+=	firefox:../../www/firefox
DEPENDS+=	mplayer:../../multimedia/mplayer
DEPENDS+=	geeqie:../../graphics/geeqie

DEPENDS+=	gliv:../../graphics/gliv

DEPENDS+=	thunderbird:../../mail/thunderbird

DEPENDS+=	evince:../../print/evince
DEPENDS+=	epdfview:../../print/epdfview
DEPENDS+=	xpdf:../../print/xpdf
DEPENDS+=	djview4:../../graphics/djview4
DEPENDS+=	calibre:../../misc/calibre

#DEPENDS+=	gpsdrive:../../geography/gpsdrive

DEPENDS+=	xephem:../../x11/xephem
DEPENDS+=	celestia:../../misc/celestia
DEPENDS+=	stellarium:../../misc/stellarium
DEPENDS+=	gpredict:../../ham/gpredict

DEPENDS+=	gnome-platform:../../meta-pkgs/gnome-platform
DEPENDS+=	gstreamer0.10-plugins:../../meta-pkgs/gstreamer0.10-plugins
DEPENDS+=	gimp:../../graphics/gimp
DEPENDS+=	cheese:../../graphics/cheese
DEPENDS+=	gucharmap:../../fonts/gucharmap
DEPENDS+=	nautilus:../../sysutils/nautilus
DEPENDS+=	ekiga:../../net/ekiga
DEPENDS+=	evolution:../../mail/evolution
DEPENDS+=	povray:../../graphics/povray

DEPENDS+=	darktable:../../graphics/darktable
DEPENDS+=	gtk2-engines:../../x11/gtk2-engines
DEPENDS+=	openoffice3:../../misc/openoffice3
DEPENDS+=	rdesktop:../../net/rdesktop
DEPENDS+=	tightvncviewer:../../net/tightvncviewer
DEPENDS+=	qemu:../../emulators/qemu

.include "../../mk/bsd.pkg.mk"
