# $NetBSD: Makefile,v 1.11 2015/01/24 23:23:48 adam Exp $

DISTNAME=	cdist-3.1.13
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	sysutils
MASTER_SITES=	https://pypi.python.org/packages/source/c/cdist/

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	http://www.nico.schottelius.org/software/cdist/
COMMENT=	Usable configuration management
LICENSE=	gnu-gpl-v3

PYTHON_VERSIONS_ACCEPTED=	34 33

.include "../../lang/python/application.mk"
.include "../../lang/python/distutils.mk"
.include "../../mk/bsd.pkg.mk"
