DISTNAME=	jakllsch-meta-cli-base-0.0.0.2012.10.21.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - base CLI
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	pkg_alternatives:../../pkgtools/pkg_alternatives
DEPENDS+=	mksh:../../shells/mksh
DEPENDS+=	nickle:../../math/nickle
DEPENDS+=	pwgen:../../sysutils/pwgen
DEPENDS+=	apg:../../security/apg
DEPENDS+=	vim:../../editors/vim

.include "../../mk/bsd.pkg.mk"
