DISTNAME=	jakllsch-meta-cli-base-0.0.0.2012.10.21.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - base CLI
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	pkg_alternatives-[0-9]*:../../pkgtools/pkg_alternatives
DEPENDS+=	mksh-[0-9]*:../../shells/mksh
DEPENDS+=	nickle-[0-9]*:../../math/nickle
DEPENDS+=	pwgen-[0-9]*:../../sysutils/pwgen
DEPENDS+=	apg-[0-9]*:../../security/apg
DEPENDS+=	vim-[0-9]*:../../editors/vim

.include "../../mk/bsd.pkg.mk"
