DISTNAME=	jakllsch-meta-cross-avr-0.0.0.2016.07.11.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - Atmel AVR8 toolchain
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=       avr-gcc-[0-9]*:../../cross/avr-gcc
DEPENDS+=       avr-gdb-[0-9]*:../../cross/avr-gdb
DEPENDS+=       avr-libc-[0-9]*:../../cross/avr-libc
DEPENDS+=       avrdude-[0-9]*:../../cross/avrdude
DEPENDS+=       dfu-programmer-[0-9]*:../../cross/dfu-programmer

.include "../../mk/bsd.pkg.mk"
