DISTNAME=	jakllsch-meta-pkgsrc-developer-0.0.0.2012.10.21.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - pkgsrc developer
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	pkg_developer:../../meta-pkgs/pkg_developer
DEPENDS+=	pkgsrc-guide-tools:../../meta-pkgs/pkgsrc-guide-tools

.include "../../mk/bsd.pkg.mk"
