DISTNAME=	jakllsch-meta-misc-0.0.0.2014.10.15.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - misc
META_PACKAGE=	yes
LICENSE=	public-domain

.include "../../lang/python/pyversion.mk"
.include "../../lang/lua/luaversion.mk"

DEPENDS+=	mksh-[0-9]*:../../shells/mksh
DEPENDS+=	netcat6-[0-9]*:../../net/netcat6
DEPENDS+=	rsync-[0-9]*:../../net/rsync
DEPENDS+=	rdiff-backup-[0-9]*:../../sysutils/rdiff-backup
DEPENDS+=	aspell-en-[0-9]*:../../textproc/aspell-en
DEPENDS+=	hunspell-[0-9]*:../../textproc/hunspell
DEPENDS+=	hunspell-en_US-[0-9]*:../../textproc/hunspell-en_US
DEPENDS+=	nickle-[0-9]*:../../math/nickle
DEPENDS+=	hexedit-[0-9]*:../../editors/hexedit
DEPENDS+=	sc-[0-9]*:../../math/sc
DEPENDS+=	flashrom-[0-9]*:../../sysutils/flashrom
DEPENDS+=	nvramtool-[0-9]*:../../sysutils/nvramtool
DEPENDS+=	pkg_alternatives-[0-9]*:../../pkgtools/pkg_alternatives
DEPENDS+=	pkgdepgraph-[0-9]*:../../pkgtools/pkgdepgraph
DEPENDS+=	libao-sun-[0-9]*:../../audio/libao-sun
DEPENDS+=	libao-oss-[0-9]*:../../audio/libao-oss
DEPENDS+=	vorbis-tools-[0-9]*:../../audio/vorbis-tools
DEPENDS+=	mpc-[0-9]*:../../audio/mpc
DEPENDS+=	ncmpc-[0-9]*:../../audio/ncmpc
DEPENDS+=	cowsay-[0-9]*:../../misc/cowsay
DEPENDS+=	lynx-[0-9]*:../../www/lynx
DEPENDS+=	links-[0-9]*:../../www/links
DEPENDS+=	w3m-[0-9]*:../../www/w3m
DEPENDS+=	lzma-[0-9]*:../../archivers/lzma
DEPENDS+=	unrar-[0-9]*:../../archivers/unrar
DEPENDS+=	pwgen-[0-9]*:../../sysutils/pwgen
DEPENDS+=	hfsutils-[0-9]*:../../sysutils/hfsutils
DEPENDS+=	ntfsprogs-[0-9]*:../../sysutils/ntfsprogs
DEPENDS+=	e2fsprogs-[0-9]*:../../sysutils/e2fsprogs
DEPENDS+=	memtestplus-[0-9]*:../../sysutils/memtestplus
DEPENDS+=	pciutils-[0-9]*:../../sysutils/pciutils
DEPENDS+=	smartmontools-[0-9]*:../../sysutils/smartmontools
DEPENDS+=	vbetool-[0-9]*:../../sysutils/vbetool
DEPENDS+=	mktemp-[0-9]*:../../sysutils/mktemp
DEPENDS+=	arena-[0-9]*:../../devel/arena
DEPENDS+=	irssi-icb-[0-9]*:../../chat/irssi-icb
DEPENDS+=	mutt-[0-9]*:../../mail/mutt-devel
DEPENDS+=	msmtp-[0-9]*:../../mail/msmtp
DEPENDS+=	cy2-gssapi-[0-9]*:../../security/cy2-gssapi
DEPENDS+=	gnupg-[0-9]*:../../security/gnupg
DEPENDS+=	mozilla-rootcerts-[0-9]*:../../security/mozilla-rootcerts
DEPENDS+=	ts-[0-9]*:../../sysutils/ts
DEPENDS+=	cdecl-[0-9]*:../../devel/cdecl

DEPENDS+=	antiword-[0-9]*:../../textproc/antiword
DEPENDS+=	antixls-[0-9]*:../../math/antixls
DEPENDS+=	unix2dos-[0-9]*:../../converters/unix2dos
DEPENDS+=	units-[0-9]*:../../math/units
DEPENDS+=	chef-[0-9]*:../../converters/chef
DEPENDS+=	jive-[0-9]*:../../misc/jive
DEPENDS+=	phoon-[0-9]*:../../time/phoon
DEPENDS+=	globe-[0-9]*:../../time/globe
DEPENDS+=	figlet-[0-9]*:../../misc/figlet
DEPENDS+=	figlet-fonts-[0-9]*:../../misc/figlet-fonts
DEPENDS+=	robotfindskitten-[0-9]*:../../games/robotfindskitten
DEPENDS+=	amaze-[0-9]*:../../games/amaze

DEPENDS+=	subversion-base-[0-9]*:../../devel/subversion-base
DEPENDS+=	git-base-[0-9]*:../../devel/git-base
DEPENDS+=	git-docs-[0-9]*:../../devel/git-docs
DEPENDS+=	libxslt-[0-9]*:../../textproc/libxslt
DEPENDS+=	tidy-[0-9]*:../../www/tidy
DEPENDS+=	ncftp3-[0-9]*:../../net/ncftp3
DEPENDS+=	${LUA_PKGPREFIX}-[0-9]*:../../lang/${LUA_PKGPREFIX}

#DEPENDS+=	python27-[0-9]*:../../lang/python27
DEPENDS+=	${PYPKGPREFIX}-readline-[0-9]*:../../devel/py-readline
DEPENDS+=	${PYPKGPREFIX}-pexpect-[0-9]*:../../devel/py-pexpect
DEPENDS+=	${PYPKGPREFIX}-ephem-[0-9]*:../../math/py-ephem
DEPENDS+=	${PYPKGPREFIX}-imaging-[0-9]*:../../graphics/py-imaging
DEPENDS+=	${PYPKGPREFIX}-cairo-[0-9]*:../../graphics/py-cairo
DEPENDS+=	${PYPKGPREFIX}-proj-[0-9]*:../../geography/py-proj
DEPENDS+=	${PYPKGPREFIX}-mpd-[0-9]*:../../audio/py-mpd
DEPENDS+=	${PYPKGPREFIX}-dns-[0-9]*:../../net/py-dns
#DEPENDS+=	${PYPKGPREFIX}-google-[0-9]*:../../net/py-google
DEPENDS+=	${PYPKGPREFIX}-audiotools-[0-9]*:../../audio/py-audiotools

DEPENDS+=	geeqie-[0-9]*:../../graphics/geeqie
DEPENDS+=	gliv-[0-9]*:../../graphics/gliv
DEPENDS+=	GraphicsMagick-[0-9]*:../../graphics/GraphicsMagick
DEPENDS+=	netpbm-[0-9]*:../../graphics/netpbm
DEPENDS+=	exiv2-[0-9]*:../../graphics/exiv2
DEPENDS+=	teTeX-[0-9]*:../../print/teTeX
DEPENDS+=	graphviz-[0-9]*:../../graphics/graphviz
DEPENDS+=	simh-[0-9]*:../../emulators/simh

DEPENDS+=	BitTornado-[0-9]*:../../net/bittornado

DEPENDS+=	ghostscript-gpl-[0-9]*:../../print/ghostscript-gpl
DEPENDS+=	djvulibre-tools-[0-9]*:../../graphics/djvulibre-tools

DEPENDS+=	mencoder-[0-9]*:../../multimedia/mencoder
DEPENDS+=	ffmpeg010-[0-9]*:../../multimedia/ffmpeg010
DEPENDS+=	ffmpeg1-[0-9]*:../../multimedia/ffmpeg1
DEPENDS+=	ffmpeg2-[0-9]*:../../multimedia/ffmpeg2

DEPENDS+=	gpsd-[0-9]*:../../geography/gpsd
DEPENDS+=	vim-[0-9]*:../../editors/vim

DEPENDS+=	cdrtools-[0-9]*:../../sysutils/cdrtools

.include "../../mk/bsd.pkg.mk"
