DISTNAME=	jakllsch-meta-misc-0.0.0.2012.02.02.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - misc
META_PACKAGE=	yes
LICENSE=	public-domain

.include "../../lang/python/pyversion.mk"

DEPENDS+=	mksh:../../shells/mksh
DEPENDS+=	netcat6:../../net/netcat6
DEPENDS+=	rsync:../../net/rsync
DEPENDS+=	rdiff-backup:../../sysutils/rdiff-backup
DEPENDS+=	aspell-english:../../textproc/aspell-english
DEPENDS+=	hunspell:../../textproc/hunspell
DEPENDS+=	hunspell-en_US:../../textproc/hunspell-en_US
DEPENDS+=	nickle:../../math/nickle
DEPENDS+=	hexedit:../../editors/hexedit
DEPENDS+=	sc:../../math/sc
DEPENDS+=	flashrom:../../sysutils/flashrom
DEPENDS+=	nvramtool:../../sysutils/nvramtool
DEPENDS+=	pkg_alternatives:../../pkgtools/pkg_alternatives
DEPENDS+=	pkgdepgraph:../../pkgtools/pkgdepgraph
DEPENDS+=	vorbis-tools:../../audio/vorbis-tools
DEPENDS+=	libao-sun:../../audio/libao-sun
DEPENDS+=	mpc:../../audio/mpc
DEPENDS+=	ncmpc:../../audio/ncmpc
DEPENDS+=	cowsay:../../misc/cowsay
DEPENDS+=	lynx:../../www/lynx
DEPENDS+=	links:../../www/links
DEPENDS+=	w3m:../../www/w3m
DEPENDS+=	lzma:../../archivers/lzma
DEPENDS+=	unrar:../../archivers/unrar
DEPENDS+=	pwgen:../../sysutils/pwgen
DEPENDS+=	hfsutils:../../sysutils/hfsutils
DEPENDS+=	ntfsprogs:../../sysutils/ntfsprogs
DEPENDS+=	e2fsprogs:../../sysutils/e2fsprogs
DEPENDS+=	memtestplus:../../sysutils/memtestplus
DEPENDS+=	pciutils:../../sysutils/pciutils
DEPENDS+=	smartmontools:../../sysutils/smartmontools
DEPENDS+=	vbetool:../../sysutils/vbetool
DEPENDS+=	mktemp:../../sysutils/mktemp
DEPENDS+=	arena:../../devel/arena
DEPENDS+=	irssi-icb:../../chat/irssi-icb
DEPENDS+=	mutt:../../mail/mutt-devel
DEPENDS+=	msmtp:../../mail/msmtp
DEPENDS+=	cy2-gssapi:../../security/cy2-gssapi
DEPENDS+=	mozilla-rootcerts:../../security/mozilla-rootcerts
DEPENDS+=	ts:../../sysutils/ts
DEPENDS+=	cdecl:../../devel/cdecl

DEPENDS+=	antiword:../../textproc/antiword
DEPENDS+=	antixls:../../math/antixls
DEPENDS+=	unix2dos:../../converters/unix2dos
DEPENDS+=	units:../../math/units
DEPENDS+=	chef:../../converters/chef
DEPENDS+=	jive:../../misc/jive
DEPENDS+=	phoon:../../time/phoon
DEPENDS+=	globe:../../time/globe
DEPENDS+=	figlet:../../misc/figlet
DEPENDS+=	figlet-fonts:../../misc/figlet-fonts
DEPENDS+=	robotfindskitten:../../games/robotfindskitten
DEPENDS+=	amaze:../../games/amaze

DEPENDS+=	subversion-base:../../devel/subversion-base
DEPENDS+=	scmgit-base:../../devel/scmgit-base
DEPENDS+=	libxslt:../../textproc/libxslt
DEPENDS+=	tidy:../../www/tidy
DEPENDS+=	ncftp3:../../net/ncftp3
DEPENDS+=	lua:../../lang/lua

#DEPENDS+=	python27:../../lang/python27
DEPENDS+=	${PYPKGPREFIX}-readline:../../devel/py-readline
DEPENDS+=	${PYPKGPREFIX}-pexpect:../../devel/py-pexpect
DEPENDS+=	${PYPKGPREFIX}-ephem:../../math/py-ephem
DEPENDS+=	${PYPKGPREFIX}-imaging:../../graphics/py-imaging
DEPENDS+=	${PYPKGPREFIX}-cairo:../../graphics/py-cairo
DEPENDS+=	${PYPKGPREFIX}-proj:../../geography/py-proj
DEPENDS+=	${PYPKGPREFIX}-mpd:../../audio/py-mpd
DEPENDS+=	${PYPKGPREFIX}-dns:../../net/py-dns
#DEPENDS+=	${PYPKGPREFIX}-google:../../net/py-google
DEPENDS+=	${PYPKGPREFIX}-audiotools:../../audio/py-audiotools

DEPENDS+=	geeqie:../../graphics/geeqie
DEPENDS+=	gliv:../../graphics/gliv
DEPENDS+=	GraphicsMagick:../../graphics/GraphicsMagick
DEPENDS+=	netpbm:../../graphics/netpbm
DEPENDS+=	exiv2:../../graphics/exiv2
DEPENDS+=	teTeX:../../print/teTeX
DEPENDS+=	graphviz:../../graphics/graphviz
DEPENDS+=	simh:../../emulators/simh

DEPENDS+=	BitTornado:../../net/bittornado

DEPENDS+=	ghostscript:../../print/ghostscript
DEPENDS+=	djvulibre-tools:../../graphics/djvulibre-tools

DEPENDS+=	mencoder:../../multimedia/mencoder
DEPENDS+=	ffmpeg:../../multimedia/ffmpeg

DEPENDS+=	gpsd:../../geography/gpsd
DEPENDS+=	vim:../../editors/vim

DEPENDS+=	cdrtools:../../sysutils/cdrtools

.include "../../mk/bsd.pkg.mk"
