DISTNAME=	jakllsch-meta-cross-arm-none-eabi-0.0.0.2016.07.11.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - ARM toolchain
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=       cross-arm-none-eabi-gcc-[0-9]*:../../cross/arm-none-eabi-gcc5
DEPENDS+=       cross-arm-none-eabi-gdb-[0-9]*:../../cross/arm-none-eabi-gdb

.include "../../mk/bsd.pkg.mk"
