DISTNAME=	jakllsch-meta-netbsd-developer-0.0.0.2012.10.21.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - netbsd developer
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	netbsd-doc:../../meta-pkgs/netbsd-doc
DEPENDS+=	netbsd-doc-print:../../meta-pkgs/netbsd-doc-print
DEPENDS+=	netbsd-www:../../meta-pkgs/netbsd-www

.include "../../mk/bsd.pkg.mk"
