DISTNAME=	jakllsch-meta-xorg-modular-0.0.0.2012.10.21.1
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - modular xorg
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	modular-xorg-protos:../../meta-pkgs/modular-xorg-protos
DEPENDS+=	modular-xorg-libs:../../meta-pkgs/modular-xorg-libs
DEPENDS+=	modular-xorg-drivers:../../meta-pkgs/modular-xorg-drivers
DEPENDS+=	modular-xorg-apps:../../meta-pkgs/modular-xorg-apps
DEPENDS+=	modular-xorg-fonts:../../meta-pkgs/modular-xorg-fonts

.include "../../mk/bsd.pkg.mk"
