DISTNAME=	jakllsch-meta-fonts-0.0.0.2013.02.02.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - fonts
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	EB-Garamond:../../fonts/EB-Garamond
DEPENDS+=	Symbola-ttf:../../fonts/Symbola-ttf
DEPENDS+=	croscorefonts:../../fonts/croscorefonts
DEPENDS+=	dejavu-ttf:../../fonts/dejavu-ttf
DEPENDS+=	droid-ttf:../../fonts/droid-ttf
DEPENDS+=	efont-unicode:../../fonts/efont-unicode
DEPENDS+=	evermono-ttf:../../fonts/evermono-ttf
DEPENDS+=	freefont-ttf:../../fonts/freefont-ttf
DEPENDS+=	freefonts:../../fonts/freefonts
DEPENDS+=	ghostscript-fonts:../../fonts/ghostscript-fonts
DEPENDS+=	liberation-ttf:../../fonts/liberation-ttf
DEPENDS+=	linux-libertine-ttf:../../fonts/linux-libertine-ttf
DEPENDS+=	inconsolata-ttf:../../fonts/inconsolata-ttf
DEPENDS+=	ms-ttf:../../fonts/ms-ttf
DEPENDS+=	roboto-fonts:../../fonts/roboto-fonts
DEPENDS+=	ricty-ttf:../../fonts/ricty-ttf
DEPENDS+=	sourcesans-fonts:../../fonts/sourcesans-fonts
DEPENDS+=	sourcecodepro-fonts:../../fonts/sourcecodepro-fonts
DEPENDS+=	terminus-font:../../fonts/terminus-font
DEPENDS+=	urw-fonts:../../fonts/urw-fonts
DEPENDS+=	vera-ttf:../../fonts/vera-ttf

.include "../../mk/bsd.pkg.mk"
