DISTNAME=	jakllsch-meta-fonts-0.0.0.2014.10.10.0
#PKGREVISION=	0
CATEGORIES=	meta-pkgs
MASTER_SITES=	
DISTFILES=	
MAINTAINER=	jakllsch@kollasch.net
COMMENT=	personal metapackage - fonts
META_PACKAGE=	yes
LICENSE=	public-domain

DEPENDS+=	EBGaramond-[0-9]*:../../fonts/EB-Garamond
DEPENDS+=	symbola-ttf-[0-9]*:../../fonts/symbola-ttf
DEPENDS+=	croscorefonts-[0-9]*:../../fonts/croscorefonts
DEPENDS+=	dejavu-ttf-[0-9]*:../../fonts/dejavu-ttf
DEPENDS+=	droid-ttf-[0-9]*:../../fonts/droid-ttf
DEPENDS+=	efont-unicode-[0-9]*:../../fonts/efont-unicode
DEPENDS+=	evermono-ttf-[0-9]*:../../fonts/evermono-ttf
DEPENDS+=	freefont-ttf-[0-9]*:../../fonts/freefont-ttf
DEPENDS+=	freefonts-[0-9]*:../../fonts/freefonts
DEPENDS+=	ghostscript-fonts-[0-9]*:../../fonts/ghostscript-fonts
DEPENDS+=	liberation-ttf-[0-9]*:../../fonts/liberation-ttf
DEPENDS+=	linux-libertine-ttf-[0-9]*:../../fonts/linux-libertine-ttf
DEPENDS+=	inconsolata-ttf-[0-9]*:../../fonts/inconsolata-ttf
DEPENDS+=	ms-ttf-[0-9]*:../../fonts/ms-ttf
DEPENDS+=	roboto-fonts-[0-9]*:../../fonts/roboto-fonts
DEPENDS+=	ricty-ttf-[0-9]*:../../fonts/ricty-ttf
DEPENDS+=	sourcesans-fonts-[0-9]*:../../fonts/sourcesans-fonts
DEPENDS+=	sourcecodepro-fonts-[0-9]*:../../fonts/sourcecodepro-fonts
DEPENDS+=	terminus-font-[0-9]*:../../fonts/terminus-font
DEPENDS+=	urw-fonts-[0-9]*:../../fonts/urw-fonts
DEPENDS+=	vera-ttf-[0-9]*:../../fonts/vera-ttf

.include "../../mk/bsd.pkg.mk"
